# Generated by Django 3.2.5 on 2023-07-20 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SolicitudesApp', '0001_initial'),
        ('ConfiguracionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspeccionM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=15)),
                ('telefonop', models.CharField(max_length=10)),
                ('telefonos', models.CharField(max_length=10)),
                ('terceraedad', models.CharField(max_length=15)),
                ('adultos', models.CharField(max_length=15)),
                ('ninos', models.CharField(max_length=15)),
                ('personadisc', models.CharField(max_length=15)),
                ('propietarioinm', models.CharField(max_length=100)),
                ('parentescosol', models.CharField(max_length=50)),
                ('latitud', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
                ('inmueble', models.CharField(max_length=10)),
                ('usoactual', models.CharField(max_length=15)),
                ('existeotraviv', models.CharField(max_length=5)),
                ('usoactualotv', models.CharField(max_length=15)),
                ('comentariosrelv', models.CharField(max_length=200)),
                ('ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolicitudesApp.solicitud')),
            ],
            options={
                'verbose_name': 'inspeccionm',
                'verbose_name_plural': 'inspeccionms',
                'db_table': 'inspeccionm',
            },
        ),
        migrations.CreateModel(
            name='ViasAccesoipm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipovia', models.CharField(max_length=35)),
                ('idipl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionMejViviendaApp.inspeccionm')),
            ],
            options={
                'verbose_name': 'viasaccesoipm',
                'verbose_name_plural': 'viasaccesoipms',
                'db_table': 'viasaccesoipm',
            },
        ),
        migrations.CreateModel(
            name='Riesgosipm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('distaludes', models.CharField(max_length=15)),
                ('disriosc', models.CharField(max_length=15)),
                ('disladerasc', models.CharField(max_length=15)),
                ('distorresantenas', models.CharField(max_length=15)),
                ('idipl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionMejViviendaApp.inspeccionm')),
            ],
            options={
                'verbose_name': 'riesgosipm',
                'verbose_name_plural': 'priesgosipms',
                'db_table': 'riesgosipm',
            },
        ),
        migrations.CreateModel(
            name='PlanMejoramientoipm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('etapas', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('idip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionMejViviendaApp.inspeccionm')),
            ],
            options={
                'verbose_name': 'planmejoramientoipm',
                'verbose_name_plural': 'planmejoramientoipms',
                'db_table': 'planmejoramientoipm',
            },
        ),
        migrations.CreateModel(
            name='pInspeccionm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('mejoraar', models.CharField(max_length=50)),
                ('esquema', models.FileField(blank=True, upload_to='documentos/')),
                ('ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolicitudesApp.solicitud')),
            ],
            options={
                'verbose_name': 'pInspeccionm',
                'verbose_name_plural': 'pInspeccionms',
                'db_table': 'pInspeccionm',
            },
        ),
        migrations.CreateModel(
            name='Inspeccionesirm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('existe', models.CharField(max_length=50)),
                ('idif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfiguracionApp.infraestructura')),
                ('idip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionMejViviendaApp.inspeccionm')),
            ],
            options={
                'verbose_name': 'inspeccionesirm',
                'verbose_name_plural': 'inspeccionesirms',
                'db_table': 'inspeccionesirm',
            },
        ),
        migrations.CreateModel(
            name='InfraestructuraInmuebleipm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('existe', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=100)),
                ('tiposistema', models.CharField(max_length=100)),
                ('idif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfiguracionApp.infraestructura')),
                ('idip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionMejViviendaApp.inspeccionm')),
            ],
            options={
                'verbose_name': 'infraestructurainmuebleipm',
                'verbose_name_plural': 'infraestructurainmuebleipms',
                'db_table': 'infraestructurainmuebleipm',
            },
        ),
        migrations.CreateModel(
            name='ImagenPInspeccionm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.FileField(blank=True, upload_to='documentos/')),
                ('idpim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionMejViviendaApp.pinspeccionm')),
            ],
            options={
                'verbose_name': 'imagenpInspeccionm',
                'verbose_name_plural': 'imagenpInspeccionms',
                'db_table': 'imagenpInspeccionm',
            },
        ),
        migrations.CreateModel(
            name='Factibilidadipm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=300)),
                ('idip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionMejViviendaApp.inspeccionm')),
            ],
            options={
                'verbose_name': 'factibilidadipm',
                'verbose_name_plural': 'factibilidadipms',
                'db_table': 'factibilidadipm',
            },
        ),
        migrations.CreateModel(
            name='DMejoramientoipm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('diasestimados', models.CharField(max_length=10)),
                ('idip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionMejViviendaApp.inspeccionm')),
            ],
            options={
                'verbose_name': 'dmejoramientoipm',
                'verbose_name_plural': 'dmejoramientoipms',
                'db_table': 'dmejoramientoipm',
            },
        ),
    ]
