from fpdf import FPDF
from datetime import date
import locale
from ClienteApp.models import *

from django.http import FileResponse
from SolicitudesApp.models import *
from ConozcaClienteApp.models import *
from django.db.models import Q



class ConozcaC(FPDF):
    
    def conozcaClie(request, id ):
        locale.setlocale(locale.LC_TIME, 'es_ES')
        fecha=date.today()
        
        try:    
            cdg=Clientedg.objects.get(iddg=id)
        except Clientedg.DoesNotExist:
            cdg=""
         
        #########################################
        idSol=cdg.ids.id
        try:
            s=  solicitud.objects.filter(id=idSol)
        except solicitud.DoesNotExist:
            s=""

        idp=cdg.ids.perfil.id
        try:
            perf=  Perfil.objects.get(id=idp)
        except solicitud.DoesNotExist:
            perf=""        
       
        
        try:
            d=  domicilio.objects.get(idSolicitud=idSol, tipo="Solicitante")
        except domicilio.DoesNotExist:
            d=""

        try:
            dpc=DatosPersonalesF.objects.get(idSolicitud=idSol, tipo="conyuge")
        except DatosPersonalesF.DoesNotExist:
            dpc=""

        try:
            dp=datosPersonales.objects.get(idSolicitud=idSol)
        except datosPersonales.DoesNotExist:
            dp=""
    ##########################################

        try:
            cdaec=  Clienteaec.objects.get(iddg=id)
        except Clienteaec.DoesNotExist:
            cdaec=""
        try: 
            cddn= Clientedn.objects.get(iddg=id)
        except Clientedn.DoesNotExist:
            cddn="" 
        try: 
            cdrrf= Clienterrf.objects.filter(iddg=id)
        except Clienterrf.DoesNotExist:
            cdrrf=""

        try: 
            cdrrfc= Clienterrf.objects.get(iddg=id)
        except Clienterrf.DoesNotExist:
            cdrrfc=""

        try:
            cdc=  Clientedc.objects.get(iddg=id)
        except Clientedc.DoesNotExist:
            cdc=""
        
        try:
            cdpbo=  Clientepbo.objects.get(iddg=id)
        except Clientepbo.DoesNotExist:
            cdpbo=""

        try:
            cpt=  Clientept.objects.get(iddg=id)
        except Clientept.DoesNotExist:
            cpt=""
        try:
            cpeps=  Clientepeps.objects.get(iddg=id)
            print(id)
        except Clientepeps.DoesNotExist:
            cpeps=""
            
        try:
            cpus=  Clientepus.objects.get(iddg=id)
            
        except Clientepus.DoesNotExist:
            cpus=""
        

        r=59
        g=93
        b=149
        aux=[0, 1, 2, 3]
        aux2=[0, 1, 2]    
        pdf=FPDF(orientation='P', unit='mm', format='Letter')
        pdf.add_page()
        #pdf.multi_cell(w=0, h=40, txt='', border=1)
        
        pdf.set_font('Arial', 'B', 12)
        pdf.set_fill_color(r,g,b)
        pdf.set_text_color(255,255,255)
        pdf.cell(w=0,h=10,txt='SOLICITUD DE CREDITO', border='TRL',  align='C', fill=True, ln=1)
        pdf.cell(w=0,h=10,txt='Para familias con ingresos provenientes de Microempresas', border='BLR',  align='C', fill=True, ln=1)
        pdf.image('TesisApp\static\TesisApp\images\logohabitatb.png', x=5, y=5, w=40, h=30)#, link=url) 
        pdf.set_font('Arial', '', 10)
        pdf.set_y(30)
        pdf.set_left_margin(10)
        pdf.set_text_color(r,g,b)
        #pdf.add_page
        pdf.set_text_color(255,255,255)
        #pdf.cell(w=0,h=5,txt='', border='B',  align='L', ln=1, fill=0)        
        pdf.cell(w=0,h=10,txt='PERSONA NATURAL', border=1,  align='C', fill=True, ln=1)
        pdf.cell(w=196,h=6,txt='DATOS GENERALES', border=1,  align='C', fill=True, ln=1)
        pdf.set_font('Arial', '', 8)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=147,h=5,txt='Nombre Completo:', border='TRL', align='L', fill=False)
        pdf.cell(w=49,h=5,txt='Código del Cliente:', border='TRL', align='L', fill=False , ln=1)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=147,h=5,txt= cdg.nombrecc if hasattr(cdg, 'nombrecc') else '' , border='BLR', align='C', fill=False)
        pdf.cell(w=49,h=5,txt=cdg.codigo if hasattr(cdg, 'codigo') else '', border='BLR', align='C', fill=False, ln=1 )
        pdf.set_text_color(r,g,b)
        pdf.cell(w=147,h=8,txt='Calidad en la que Actúa: ' , border=1, align='L', fill=False)
        pdf.set_xy(50, 55)
        if cdg.calidadactua=='Cliente':
           
            pdf.cell(w=30,h=10,txt='Cliente', border=0,  align='L', fill=0)
            pdf.set_xy(64, 58)
            pdf.cell(w=4,h=4,txt='X', border=1,  align='L', fill=0)
            pdf.set_xy(75, 55)
            pdf.cell(w=20,h=10,txt='Fiador', border=0,  align='L', fill=0)
            pdf.set_xy(90, 58)
            pdf.cell(w=4,h=4,txt='', border=1,  align='L', fill=0)
            pdf.cell(w=62, h=5, border=0)
        else:
            
            pdf.cell(w=30,h=10,txt='Cliente', border=0,  align='L', fill=0)
            pdf.set_xy(64, 58)
            pdf.cell(w=4,h=4,txt='', border=1,  align='L', fill=0)
            pdf.set_xy(75, 55)
            pdf.cell(w=20,h=10,txt='Fiador', border=0,  align='L', fill=0)
            pdf.set_xy(90, 58)
            pdf.cell(w=4,h=4,txt='X', border=1,  align='L', fill=0)
            pdf.cell(w=62, h=5, border=0)
        pdf.set_xy(157,56)
        pdf.cell(w=20,h=8,txt='Estado Civil: ', border='LTB', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.multi_cell(w=0,h=8,txt= dp.estadocivilC if hasattr(dp, 'estadocivilC') else '', border='RTB', align='L', fill=False)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=147,h=5,txt='Conocido por: (Solo si lo dice el DUI)', border='TRL', align='L', fill=False)
        pdf.multi_cell(w=0,h=5,txt='Profesión según DUI:', border='TRL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=147,h=5,txt=cdg.conocidocomo if hasattr(cdg, 'conocidocomo') else '', border='BLR', align='C', fill=False)
        pdf.multi_cell(w=49,h=5,txt=cdg.profesiondui if hasattr(cdg, 'profesiondui') else '', border='BLR', align='C', fill=False)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=147,h=5,txt='Lugar y fecha de nacimiento:', border='TRL', align='L', fill=False)
        pdf.cell(w=49,h=5,txt='Nacionalidad:', border='TRL', align='L', fill=False , ln=1)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=147,h=5,txt= (dp.lugarnaciC if hasattr(dp, 'lugarnaciC') else '')+', '+ (perf.fechan.strftime("%d/%m/%Y") if hasattr(perf, 'fechan') else ''), border='BLR', align='C', fill=False)
        pdf.cell(w=49,h=5,txt=perf.nacionalidad if hasattr(perf, 'nacionalidad') else '', border='BLR', align='C', fill=False, ln=1 )
        pdf.set_text_color(r,g,b)
        pdf.cell(w=45,h=5,txt='Documento de Identidad:', border='TRL', align='L', fill=False)
        pdf.cell(w=43,h=5,txt='No. Documento:', border='TRL', align='L', fill=False)
        pdf.cell(w=59,h=5,txt='Fecha de Vencimiento:', border='TRL', align='L', fill=False)
        pdf.multi_cell(w=0,h=5,txt='Ocupación o Actividad actual:', border='TRL', align='L', fill=False)
        pdf.cell(w=45,h=5,txt='', border='BLR', align='C', fill=False)
        pdf.set_xy(10, 88)
        if cdg.docidentidad=='DUI':
           
            pdf.cell(w=8,h=5,txt='DUI', border=0,  align='L', fill=0)
            pdf.set_xy(17, 89)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(25, 88)
            pdf.cell(w=8,h=5,txt='PAS', border=0,  align='L', fill=0)
            pdf.set_xy(33, 89)
            pdf.cell(w=3,h=3,txt='', border=1,  align='L', fill=0)
            pdf.set_xy(38, 88)
            pdf.cell(w=7,h=5,txt='CR', border=0,  align='C', fill=0)
            pdf.set_xy(45, 89)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            

        elif cdg.docidentidad=='PAS':
           
            pdf.cell(w=8,h=5,txt='DUI', border=0,  align='L', fill=0)
            pdf.set_xy(17, 89)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(25, 88)
            pdf.cell(w=8,h=5,txt='PAS', border=0,  align='L', fill=0)
            pdf.set_xy(33, 89)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='L', fill=0)
            pdf.set_xy(38, 88)
            pdf.cell(w=7,h=5,txt='CR', border=0,  align='C', fill=0)
            pdf.set_xy(45, 89)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            
        else:
            
            pdf.cell(w=8,h=5,txt='DUI', border=0,  align='L', fill=0)
            pdf.set_xy(17, 89)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(25, 88)
            pdf.cell(w=8,h=5,txt='PAS', border=0,  align='L', fill=0)
            pdf.set_xy(33, 89)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='L', fill=0)
            pdf.set_xy(38, 88)
            pdf.cell(w=7,h=5,txt='CR', border=0,  align='C', fill=0)
            pdf.set_xy(45, 89)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)

        pdf.set_text_color(0,0,0)   
        pdf.set_xy(55,89)
        pdf.cell(w=43,h=5,txt=cdg.numerodoc if hasattr(cdg, 'numerodoc') else '', border='BLR', align='C', fill=False)
        pdf.cell(w=59,h=5,txt=cdg.fechavdoc.strftime("%d/%m/%Y") if hasattr(cdg, 'fechavdoc') else '', border='BLR', align='C', fill=False)
        pdf.multi_cell(w=0,h=5,txt=perf.idocu.ocupacion if hasattr(perf, 'idocu') else '', border='BLR', align='C', fill=False)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=45,h=5,txt='N° de NIT:', border='TRL', align='L', fill=False)
        pdf.cell(w=43,h=5,txt='No. Registro de IVA:', border='TRL', align='L', fill=False)
        pdf.cell(w=59,h=5,txt='Correo Electrónico:', border='TRL', align='L', fill=False)
        pdf.cell(w=27,h=5,txt='Teléfono de Celular: ', border='TL', align='L', fill=False )
        pdf.set_text_color(0,0,0)
        pdf.cell(w=22,h=5,txt= perf.telefono if hasattr(perf, 'telefono') else '', border='TR', align='L', fill=False , ln=1)
        pdf.cell(w=45,h=5,txt='--------------------', border='BLR', align='C', fill=False)
        pdf.cell(w=43,h=5,txt='--------------------', border='BLR', align='C', fill=False)       
        pdf.cell(w=59,h=5,txt=perf.correo, border='BLR', align='C', fill=False)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=21,h=5,txt='Teléfono Fijo :', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=28,h=5,txt=cdg.telfijo if hasattr(cdg, 'telfijo') else '', border='BR', align='L', fill=False, ln=1 )
        pdf.set_text_color(r,g,b)
        pdf.cell(w=147,h=5,txt='Dirección domicilio:', border='TRL', align='L', fill=False)
        pdf.cell(w=49,h=5,txt='Tiempo de residir en esta dirección:', border='TRL', align='L', fill=False , ln=1)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=147,h=5,txt=perf.direccion if hasattr(perf, 'direccion') else '', border='BLR', align='C', fill=False)
        pdf.cell(w=49,h=5,txt=d.resideDesde if hasattr(d, 'resideDesde') else '', border='BLR', align='C', fill=False, ln=1 )
        pdf.set_text_color(r,g,b)
        pdf.cell(w=37,h=5,txt='Giro, según tarjeta de IVA: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=110,h=5,txt=' --------------------------------------------', border='BR', align='L', fill=False)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=31,h=5,txt='Estatus de la propiedad:  ', border='BL', align='L', fill=False )
        pdf.set_text_color(0,0,0)
        pdf.cell(w=18,h=5,txt= cdg.estatuspropiedad if hasattr(cdg, 'estatuspropiedad') else '', border='BR', align='L', fill=False , ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=30,h=5,txt='Nombre del Cónyuge:  ', border='LTB', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=0,h=5,txt=cdg.nombreconyuge if hasattr(cdg, 'nombreconyuge') else '', border='TRB', align='L', fill=False, ln=1)
        pdf.set_text_color(255,255,255)
        pdf.multi_cell(w=0,h=6,txt='ACTIVIDADES ECONOMICAS DEL CLIENTE', border=1,  align='C', fill=True)
        pdf.set_text_color(r,g,b)
        pdf.multi_cell(w=0,h=5,txt='', border=1, align='L', fill=False)
        pdf.set_xy(10, 130)

        if cdaec!="" and cdaec.tipoact=='Empleado':
           
            pdf.cell(w=20,h=5,txt='Empleado', border=0,  align='L', fill=0)
            pdf.set_xy(25, 131)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(35, 130)
            pdf.cell(w=20,h=5,txt='Negocio Propio', border=0,  align='L', fill=0)
            pdf.set_xy(60, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='L', fill=0)
            pdf.set_xy(70, 130)
            pdf.cell(w=15,h=5,txt='Dependiente', border=0,  align='C', fill=0)
            pdf.set_xy(90, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(100, 130)
            pdf.cell(w=10,h=5,txt='Otro', border=0,  align='C', fill=0)
            pdf.set_xy(110, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(85, 130)
            pdf.multi_cell(w=0,h=5, txt='', border=0)

        elif cdaec!="" and cdaec.tipoact=='Negocio Propio':
           
            pdf.cell(w=20,h=5,txt='Empleado', border=0,  align='L', fill=0)
            pdf.set_xy(25, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(35, 130)
            pdf.cell(w=20,h=5,txt='Negocio Propio', border=0,  align='L', fill=0)
            pdf.set_xy(60, 131)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='L', fill=0)
            pdf.set_xy(70, 130)
            pdf.cell(w=15,h=5,txt='Dependiente', border=0,  align='C', fill=0)
            pdf.set_xy(90, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(100, 130)
            pdf.cell(w=10,h=5,txt='Otro', border=0,  align='C', fill=0)
            pdf.set_xy(110, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(85, 130)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        elif cdaec!="" and cdaec.tipoact=='Dependiente':
           
            pdf.cell(w=20,h=5,txt='Empleado', border=0,  align='L', fill=0)
            pdf.set_xy(25, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(35, 130)
            pdf.cell(w=20,h=5,txt='Negocio Propio', border=0,  align='L', fill=0)
            pdf.set_xy(60, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='L', fill=0)
            pdf.set_xy(70, 130)
            pdf.cell(w=15,h=5,txt='Dependiente', border=0,  align='C', fill=0)
            pdf.set_xy(90, 131)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(100, 130)
            pdf.cell(w=10,h=5,txt='Otro', border=0,  align='C', fill=0)
            pdf.set_xy(110, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(85, 130)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        else:
            
            pdf.cell(w=20,h=5,txt='Empleado', border=0,  align='L', fill=0)
            pdf.set_xy(25, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(35, 130)
            pdf.cell(w=20,h=5,txt='Negocio Propio', border=0,  align='L', fill=0)
            pdf.set_xy(60, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='L', fill=0)
            pdf.set_xy(70, 130)
            pdf.cell(w=15,h=5,txt='Dependiente', border=0,  align='C', fill=0)
            pdf.set_xy(90, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(100, 130)
            pdf.cell(w=10,h=5,txt='Otro', border=0,  align='C', fill=0)
            pdf.set_xy(110, 131)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(85, 130)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        pdf.cell(w=40,h=5,txt='Especifique el lugar de trabajo: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=0,h=5,txt= str(cdaec.lugartrab) if hasattr(cdaec, 'lugartrab') else '', border='BR', align='L', fill=False, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=30,h=5,txt='cargo que desempeña: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=117,h=5,txt= cdaec.cargodes if hasattr(cdaec, 'cargodes') else '', border='BR', align='L', fill=False)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=26,h=5,txt='Tiempo de Laborar: ', border='BL', align='L', fill=False )
        pdf.set_text_color(0,0,0)
        pdf.cell(w=23,h=5,txt=cdaec.tiempolaborar if hasattr(cdaec, 'tiempolaborar') else '', border='BR', align='L', fill=False , ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=36,h=5,txt='Procedencia de los Fondos: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=0,h=5,txt= cdaec.procedenciafod if hasattr(cdaec, 'procedenciafod') else '', border='BR', align='L', fill=False, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=52,h=5,txt='Rango Ingreso Mensual si es empleado: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=95,h=5,txt= cdaec.rangoingresosemp if hasattr(cdaec, 'rangoingresosemp') else '', border='BR', align='L', fill=False)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=20,h=5,txt='Otros Ingresos: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=29,h=5,txt= cdaec.otrosingresos if hasattr(cdaec, 'otrosingresos') else '', border='BR', align='L', fill=False, ln=1 )
        pdf.set_text_color(r,g,b)
        pdf.cell(w=64,h=5,txt='De existir otros ingresos, describa la procedencia: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=0,h=5,txt= cdaec.procedenciaoi if hasattr(cdaec, 'procedenciaoi') else '', border='BR', align='L', fill=False, ln=1)
        pdf.set_text_color(255,255,255)
        pdf.cell(w=196,h=6,txt='DATOS DEL NEGOCIO', border=1,  align='C', fill=True, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=30,h=5,txt='Nombre del negocio: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=0,h=5,txt= cddn.nombreneg if hasattr(cddn, 'nombreneg') else '', border='BR', align='L', fill=False, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=70,h=5,txt='Describa los productos y/o servicios que comercializa: ' , border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=0,h=5,txt=cddn.prodserv if hasattr(cddn, 'prodserv') else '', border='BR', align='L', fill=False, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=30,h=5,txt='Dirección del negocio: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=0,h=5,txt=cddn.direccionneg if hasattr(cddn, 'direccionneg') else '', border='BR', align='L', fill=False, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=40,h=5,txt='Fecha de inicio de actividades: ' , border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=36,h=5,txt= cddn.fechaia.strftime("%d/%m/%Y") if hasattr(cddn, 'fechaia') else '', border='BR', align='L', fill=False)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=56,h=5,txt='Rango de ingresos mensuales del negocio: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=34,h=5,txt= cddn.rangoingresos if hasattr(cddn, 'rangoingresos') else '', border='BR', align='L', fill=False)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=21,h=5,txt='Otros ingresos: ', border='BL', align='L', fill=False )
        pdf.set_text_color(0,0,0)
        pdf.cell(w=9,h=5,txt= cddn.otrosingresos if hasattr(cddn, 'otrosingresos') else '', border='BR', align='L', fill=False , ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=65,h=5,txt='De existir otros ingresos, describa la procedencia: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=0,h=5,txt=cddn.procedenciaoi if hasattr(cddn, 'procedenciaoi') else '', border='BR', align='L', fill=False, ln=1)
        pdf.set_text_color(255,255,255)
        pdf.multi_cell(w=196,h=6,txt='RECIBE REMESAS FAMILIARES', border=1,  align='C', fill=True)
        pdf.set_xy(145, 192)
        if cdrrfc != "" and str(cdrrfc.rremesa) =='Si':
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(150, 193)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(160, 192)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(168, 193)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(85, 192)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        else:
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(150, 193)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(160, 192)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(168, 193)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(175, 192)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=75,h=5,txt='Nombre del remitente:', border=1, align='L', fill=False)
        pdf.cell(w=40,h=5,txt='Parentesco:', border=1, align='L', fill=False)
        pdf.cell(w=51,h=5,txt='Pais de origen:', border=1, align='L', fill=False)
        pdf.cell(w=30,h=5,txt='Monto:', border=1, align='L', fill=False , ln=1)

        pdf.set_text_color(0,0,0)
        if cdrrf!='' and len(cdrrf)>0:
            for rf in cdrrf:
                pdf.cell(w=75,h=5,txt=rf.nombreremitente or '', border=1,  align='L', fill=0)
                pdf.cell(w=40,h=5,txt=rf.parentesco or '', border=1,  align='L', fill=0)
                pdf.cell(w=51,h=5,txt=rf.paisorigenr or '', border=1,  align='L', fill=0)
                pdf.cell(w=30,h=5,txt=str(rf.monto) or '', border=1,  align='L', fill=0, ln=1)

        else:
            
            for i in aux:
                pdf.cell(w=75,h=5,txt='', border=1,  align='L', fill=0)
                pdf.cell(w=40,h=5,txt='', border=1,  align='L', fill=0)
                pdf.cell(w=51,h=5,txt='', border=1,  align='L', fill=0)
                pdf.cell(w=30,h=5,txt='', border=1,  align='L', fill=0, ln=1)


        
        pdf.set_text_color(255,255,255)
        pdf.cell(w=196,h=6,txt='DECLARACION DEL CLIENTE O FIADOR EN OPERACIONES ACTIVAS', border=1,  align='C', fill=True, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=81,h=5,txt='Clasificación del credito: ', border=1, align='L', fill=False)
        pdf.set_xy(45, 213)
        if cdc!="" and cdc.clasifcredito=='Mejora':
            pdf.cell(w=5,h=5,txt='Mejora', border=0,  align='L', fill=0)
            pdf.set_xy(58, 214)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(65, 213)
            pdf.cell(w=5,h=5,txt='Vivienda', border=0,  align='L', fill=0)
            pdf.set_xy(80, 214)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)            
        else:
            pdf.cell(w=5,h=5,txt='Mejora', border=0,  align='L', fill=0)
            pdf.set_xy(58, 214)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(65, 213)
            pdf.cell(w=5,h=5,txt='Vivienda', border=0,  align='L', fill=0)
            pdf.set_xy(80, 214)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            
        pdf.set_xy(91, 213)
        pdf.cell(w=55,h=5,txt='Monto: '+ cdc.montodc if hasattr(cdc, 'montodc') else '', border=1, align='L', fill=False)
        pdf.cell(w=60,h=5,txt='Cuota: ' + cdc.cuotadc if hasattr(cdc, 'cuotadc') else '', border=1, align='L', fill=False, ln=1)
        
        pdf.multi_cell(w=81,h=5,txt='Tiene proyectado realizar pagos  adicionales a las cuotas pactadas? ', border='LRT', align='L', fill=False)
        pdf.cell(w=81,h=10,txt='', border='LRB', align='L', fill=False)
        pdf.set_xy(25, 223)
        if  cdc!="" and cdc.rpagosadic =='Si':
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(31, 224)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(40, 223)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(47, 224)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(60, 223)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        else:
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(31, 224)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(40, 223)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(47, 224)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(60, 223)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        
        pdf.set_xy(91,218)
        pdf.multi_cell(w=115,h=20,txt='Si su respuesta es afirmativa, indique la procedencia de los fondos: ' + cdc.procpagosadic if hasattr(cdc, 'procpagosadic') else '', border=1, align='L', fill=False)

        pdf.add_page()
        pdf.set_text_color(255,255,255)
        pdf.cell(w=196,h=6,txt='PERSONA BENEFICIARIA DE LA OPERACIÓN       No Aplica', border=1,  align='C', fill=True, ln=1)
        
        if cdpbo!="" and cdpbo.noaplica =='No':                  
            pdf.set_xy(150, 11)
            pdf.cell(w=4,h=4,txt='X', border=1,  align='L', fill=True)
            pdf.cell(w=62, h=5, border=0)
        else:    
            pdf.set_xy(150, 11)
            pdf.cell(w=4,h=4,txt='', border=1,  align='L', fill=0)
            pdf.cell(w=62, h=5, border=0)

        pdf.set_text_color(r,g,b)
        pdf.cell(w=196,h=5,txt='En los casos que el préstamo sea para uso de otro beneficiario favor completar la siguiente información en todos sus campos sin excepción alguna:', border=1, align='L', fill=False, ln=1)
        pdf.cell(w=196,h=5,txt='Nombre completo del beneficiario:' + str(cdpbo.nombrecomp if hasattr(cdpbo, 'nombrecomp') else' --------------------------------------------------') or '', border=1, align='L', fill=False, ln=1)
        pdf.cell(w=196,h=5,txt='Dirección permanente del beneficiario:'+ str(cdpbo.direccionp if hasattr(cdpbo, 'direccionp') else' ---------------------------------------------') or '', border=1, align='L', fill=False, ln=1)
        pdf.cell(w=196,h=5,txt='Tipo y número de documento de indentificación:'+ str(cdpbo.tdocumento if hasattr(cdpbo, 'tdocumento') else' -------------------------------------') or '', border=1, align='L', fill=False, ln=1)
        pdf.cell(w=196,h=5,txt='El beneficiario es Persona Expuesta Politicamente:', border=1, align='L', fill=False, ln=1)

        pdf.set_xy(75, 31)
        if  cdpbo!="" and cdpbo.benefpeps =='Si':
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(80, 32)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(85, 31)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(92, 32)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(61, 31)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        else:
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(80, 32)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(85, 31)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(92, 32)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(60, 31)
            pdf.multi_cell(w=0,h=5, txt='', border=0)


        pdf.cell(w=196,h=5,txt='', border='BT', align='L', fill=False, ln=1)
        pdf.set_text_color(255,255,255)
        pdf.cell(w=196,h=6,txt='PERFIL DE TRANSACCONES(PRODUCTOS ACTUALES CON LA ASOCIACION)', border=1,  align='C', fill=True, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=20,h=5,txt='PRESTAMOS: ', border='LBT', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=0,h=5,txt= cpt.prestamos if hasattr(cpt, 'prestamos') else '', border='RBT', align='L', fill=False, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=30,h=5,txt='Otros(especificar): ' , border='LBT', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=0,h=5,txt= cpt.espotros if hasattr(cpt, 'espotros') else '', border='RBT', align='L', fill=False, ln=1)
        pdf.set_text_color(255,255,255)
        pdf.cell(w=196,h=6,txt='PERSONA EXPUESTA POLITICAMENTE(PEPs)', border=1,  align='C', fill=True, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=147,h=10,txt='¿Es usted una Persona Expuesta Politicamente(PEPs)?:', border=1, align='L', fill=False)
        
        pdf.set_xy(85, 66)
        if  cpeps!="" and cpeps.ustedpeps =='Si':
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(93, 67)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(110, 66)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(118, 67)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(130, 67)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        else:

            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(93, 67)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(110, 66)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(118, 67)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(130, 67)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        

        pdf.set_xy(157, 63)
        pdf.cell(w=49,h=10,txt='PEPs POR PARENTESCO:', border=1, align='C', fill=False , ln=1)
        pdf.cell(w=147,h=10,txt='¿Tiene relación con alguna Persona Expuesta Politicamnete (PEPs)?:', border=1, align='L', fill=False)
        pdf.set_xy(120, 76)
        if  cpeps!="" and cpeps.relacionpeps =='Si':
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(128, 77)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(135, 76)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(143, 77)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(148, 77)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        else:
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(128, 77)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(135, 76)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(143, 77)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(148, 77)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        

        pdf.set_xy(157, 73)
        pdf.cell(w=15,h=10,txt='Grado:', border=1, align='C', fill=False )
        pdf.cell(w=34,h=10,txt='Parentesco:', border=1, align='C', fill=False , ln=1)

        pdf.multi_cell(w=147,h=5,txt='¿Si su respuesta es afirmativa indique el nombre y/o parentesco de la Persona Expuesta Politicamente (PEPs)mcon la que tiene relacion y el puesto que desempeña?:', border=1, align='L', fill=False )
        pdf.set_xy(157,83)
        pdf.cell(w=15,h=10,txt='1er:', border=1, align='L', fill=False )
        pdf.set_xy(172,83)
        pdf.set_font('Arial', '', 7)
        if cpeps!="" and str(cpeps.grado) =='Primero':
            print("hola")
            if cpeps!="" and str(cpeps.parentesco) =='Padre': 
                pdf.cell(w=11,h=3,txt='Padre-', border=1, align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Madre-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Suegro-', border='R', align='L', fill=False )
                pdf.set_xy(172,86)
                pdf.cell(w=11,h=3,txt='Suegra-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Hijo-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Hija-', border='R', align='L', fill=False )
                pdf.set_xy(172,89)
                pdf.cell(w=11,h=4,txt='Yerno-', border='', align='L', fill=False )
                pdf.cell(w=11,h=4,txt='Nuera', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.parentesco) =='Madre':
                pdf.cell(w=11,h=3,txt='Padre-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Madre-', border=1, align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Suegro-', border='R', align='L', fill=False )
                pdf.set_xy(172,86)
                pdf.cell(w=11,h=3,txt='Suegra-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Hijo-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Hija-', border='R', align='L', fill=False )
                pdf.set_xy(172,89)
                pdf.cell(w=11,h=4,txt='Yerno-', border='', align='L', fill=False )
                pdf.cell(w=11,h=4,txt='Nuera', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.parentesco) =='Suegro':
                pdf.cell(w=11,h=3,txt='Padre-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Madre-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Suegro-', border='1', align='L', fill=False )
                pdf.set_xy(172,86)
                pdf.cell(w=11,h=3,txt='Suegra-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Hijo-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Hija-', border='R', align='L', fill=False )
                pdf.set_xy(172,89)
                pdf.cell(w=11,h=4,txt='Yerno-', border='', align='L', fill=False )
                pdf.cell(w=11,h=4,txt='Nuera', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.parentesco) =='Suegra':
                pdf.cell(w=11,h=3,txt='Padre-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Madre-', border='B', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Suegro-', border='R', align='L', fill=False )
                pdf.set_xy(172,86)
                pdf.cell(w=11,h=3,txt='Suegra-', border='BLRT', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Hijo-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Hija-', border='R', align='L', fill=False )
                pdf.set_xy(172,89)
                pdf.cell(w=11,h=4,txt='Yerno-', border='', align='L', fill=False )
                pdf.cell(w=11,h=4,txt='Nuera', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.parentesco) =='Hijo':
                pdf.cell(w=11,h=3,txt='Padre-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Madre-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Suegro-', border='R', align='L', fill=False )
                pdf.set_xy(172,86)
                pdf.cell(w=11,h=3,txt='Suegra-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Hijo-', border=1, align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Hija-', border='R', align='L', fill=False )
                pdf.set_xy(172,89)
                pdf.cell(w=11,h=4,txt='Yerno-', border='', align='L', fill=False )
                pdf.cell(w=11,h=4,txt='Nuera', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.parentesco) =='Hija':
                pdf.cell(w=11,h=3,txt='Padre-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Madre-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Suegro-', border='R', align='L', fill=False )
                pdf.set_xy(172,86)
                pdf.cell(w=11,h=3,txt='Suegra-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Hijo-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Hija-', border='BRLT', align='L', fill=False )
                pdf.set_xy(172,89)
                pdf.cell(w=11,h=4,txt='Yerno-', border='', align='L', fill=False )
                pdf.cell(w=11,h=4,txt='Nuera', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.parentesco) =='Yerno':
                pdf.cell(w=11,h=3,txt='Padre-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Madre-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Suegro-', border='R', align='L', fill=False )
                pdf.set_xy(172,86)
                pdf.cell(w=11,h=3,txt='Suegra-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Hijo-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Hija-', border='R', align='L', fill=False )
                pdf.set_xy(172,89)
                pdf.cell(w=11,h=4,txt='Yerno-', border='1', align='L', fill=False )
                pdf.cell(w=11,h=4,txt='Nuera', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.parentesco) =='Nuera':
                pdf.cell(w=11,h=3,txt='Padre-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Madre-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Suegro-', border='R', align='L', fill=False )
                pdf.set_xy(172,86)
                pdf.cell(w=11,h=3,txt='Suegra-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Hijo-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Hija-', border='R', align='L', fill=False )
                pdf.set_xy(172,89)
                pdf.cell(w=11,h=4,txt='Yerno-', border='', align='L', fill=False )
                pdf.cell(w=11,h=4,txt='Nuera', border='B', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='', border='R', align='L', fill=False )
            else:
                pdf.cell(w=11,h=3,txt='Padre-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Madre-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Suegro-', border='R', align='L', fill=False )
                pdf.set_xy(172,86)
                pdf.cell(w=11,h=3,txt='Suegra-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Hijo-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Hija-', border='R', align='L', fill=False )
                pdf.set_xy(172,89)
                pdf.cell(w=11,h=4,txt='Yerno-', border='', align='L', fill=False )
                pdf.cell(w=11,h=4,txt='Nuera', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='', border='R', align='L', fill=False )
        else:
            pdf.cell(w=11,h=3,txt='Padre-', border='L', align='L', fill=False )
            pdf.cell(w=11,h=3,txt='Madre-', border='', align='L', fill=False )
            pdf.multi_cell(w=0,h=3,txt='Suegro-', border='R', align='L', fill=False )
            pdf.set_xy(172,86)
            pdf.cell(w=11,h=3,txt='Suegra-', border='L', align='L', fill=False )
            pdf.cell(w=11,h=3,txt='Hijo-', border='', align='L', fill=False )
            pdf.multi_cell(w=0,h=3,txt='Hija-', border='R', align='L', fill=False )
            pdf.set_xy(172,89)
            pdf.cell(w=11,h=4,txt='Yerno-', border='', align='L', fill=False )
            pdf.cell(w=11,h=4,txt='Nuera', border='', align='L', fill=False )
            pdf.multi_cell(w=0,h=4,txt='', border='R', align='L', fill=False )
                #pdf.multi_cell(w=11,h=3,txt='Nuera', border='R', align='L', fill=False )
            #pdf.multi_cell(w=34,h=5,txt='Padre-Madre-Suegro-Suegra- Hijo-Hija-Yerno-Nuera', border=1, align='L', fill=False)
        pdf.set_font('Arial', '', 8)
        pdf.cell(w=13,h=5,txt='Nombre: ', border='L', align='L', fill=False )
        pdf.cell(w=129,h=5,txt=cpeps.nombrep if hasattr(cpeps, 'nombrep') else '', border='BT', align='L', fill=False )
        pdf.cell(w=5,h=5,txt=' ', border='T', align='L', fill=False )
        pdf.set_xy(157,93)
        pdf.cell(w=15,h=5,txt='', border='LR', align='L', fill=False, ln=1 )       
        pdf.cell(w=32,h=5,txt='Puesto que desempeña:', border='L', align='L', fill=False )
        pdf.cell(w=110,h=5,txt=cpeps.puestdesemp if hasattr(cpeps, 'puestdesemp') else '', border='BT', align='L', fill=False )
        pdf.cell(w=5,h=5,txt=' ', border='R', align='L', fill=False )
        pdf.set_xy(157,98)
        pdf.cell(w=15,h=5,txt='2er:', border='LR', align='L', fill=False , ln=1)
        pdf.cell(w=147,h=5,txt='Periodo de gestión:         Desde: '+ (cpeps.pergestiondesde if hasattr(cpeps, 'pergestiondesde') else '') + '       Hasta:'+ (cpeps.pergestionhasta if hasattr(cpeps, 'pergestionhasta') else ''), border='RL', align='L', fill=False )
        pdf.set_xy(157,103)
        pdf.cell(w=15,h=5,txt='', border='LR', align='L', fill=False )
        pdf.set_xy(172,93)
        pdf.set_font('Arial', '', 7)
        if cpeps!="" and str(cpeps.grado) =='Segundo':
            if cpeps!="" and str(cpeps.parentesco) =='Abuelo': 
                pdf.cell(w=10,h=4,txt='Abuelo-', border='LBT', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=11,h=4,txt='Hermana-', border='L', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.parentesco) =='Abuela':
                pdf.cell(w=10,h=4,txt='Abuelo-', border='LT', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='TB', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=11,h=4,txt='Hermana-', border='L', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.parentesco) =='Hermano':
                pdf.cell(w=10,h=4,txt='Abuelo-', border='LT', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RTB', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=11,h=4,txt='Hermana-', border='L', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.parentesco) =='Hermana':
                pdf.cell(w=10,h=4,txt='Abuelo-', border='LT', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=11,h=4,txt='Hermana-', border='LB', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.parentesco) =='Cuñado':
                pdf.cell(w=10,h=4,txt='Abuelo-', border='LT', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=11,h=4,txt='Hermana-', border='L', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='B', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.parentesco) =='Cuñada':
                pdf.cell(w=10,h=4,txt='Abuelo-', border='LT', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=11,h=4,txt='Hermana-', border='L', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='RB', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.parentesco) =='Nieto':
                pdf.cell(w=10,h=4,txt='Abuelo-', border='LT', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=11,h=4,txt='Hermana-', border='L', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='B', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.parentesco) =='Nieta':
                pdf.cell(w=10,h=4,txt='Abuelo-', border='LT', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=11,h=4,txt='Hermana-', border='L', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='B', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.parentesco) =='Concuñado':
                pdf.cell(w=10,h=4,txt='Abuelo-', border='LT', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=11,h=4,txt='Hermana-', border='L', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='RB', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.parentesco) =='Abuelos del conyuge':
                pdf.cell(w=10,h=4,txt='Abuelo-', border='LT', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=11,h=4,txt='Hermana-', border='L', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='BR', align='L', fill=False )
            else:
                pdf.cell(w=10,h=4,txt='Abuelo-', border='LT', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=10,h=4,txt='Hermana-', border='L', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )
        else:
            pdf.cell(w=10,h=4,txt='Abuelo-', border='LT', align='L', fill=False )
            pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
            pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
            pdf.set_xy(172,97)
            pdf.cell(w=11,h=4,txt='Hermana-', border='L', align='L', fill=False )
            pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
            pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
            pdf.set_xy(172,100)
            pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
            pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
            pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
            pdf.set_xy(172,104)
            pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )
            #pdf.multi_cell(w=34,h=3.75,txt='Abuelo-Abuela-Hemano- Hermana- Cuñado-Cuñada- Nieto- Nieta-Concuñado- abuelos del cónyuge:', border=1, align='L', fill=False )
        #pdf.cell(w=10,h=3,txt='', border='LR', align='L', fill=False )
        pdf.set_font('Arial', '', 8)
        pdf.cell(w=196,h=5,txt=' YO: '+ cdg.nombrecc if hasattr(cdg, 'nombrecc') else '' , border=1, align='L', fill=False, ln=1)
        pdf.multi_cell(w=196,h=5,txt='Declaro bajo juramento que los datos antes descritos son verdaderos y que mis ingresos provienen de actividades enteramente licitas, por  consiguiente, dichos fondos no se encuentran relacionados bajo ninguna circunstancia con hechos o actividades criminales relacionadas con el  narcotráfico y delitos conexos con el Labado de Dinero y Activos, tampoco con situaciones en contra de la Ley Contra el Labado de Dinero y de  Activos de la Republica de El Salvador. Además declaro que me someto a cualquier tipo de investigación necesaria para establecer la procedencia y el  origen de los fondos de mi operación. Por último declaro que éste formulario ha sido completado por mi y/o en mi presencia y que la información provista  es verdadera. ' , border=1, align='L', fill=False)
        pdf.cell(w=4,h=10,txt='F: ', border='L', align='L', fill=False )
        pdf.cell(w=70,h=10,txt=' ', border='BT', align='L', fill=False )  
        pdf.cell(w=37,h=10,txt=' ', border='T', align='L', fill=False )     
        pdf.cell(w=20,h=10,txt='Lugar y Fecha: ', border='T', align='L', fill=False )
        pdf.cell(w=60,h=10,txt=' ', border='BT', align='L', fill=False )
        pdf.cell(w=5,h=10,txt=' ', border='TR', align='L', fill=False, ln=1 )
        pdf.cell(w=4,h=5,txt=' ', border='L', align='L', fill=False )
        pdf.cell(w=70,h=5,txt='Firma del Cliente ', border='', align='C', fill=False )  
        pdf.cell(w=37,h=5,txt=' ', border='', align='L', fill=False )     
        pdf.cell(w=20,h=5,txt='', border='', align='L', fill=False )
        pdf.cell(w=60,h=5,txt=' ', border='', align='L', fill=False )
        pdf.cell(w=5,h=5,txt=' ', border='R', align='L', fill=False, ln=1 )
        pdf.cell(w=4,h=5,txt=' ', border='LB', align='L', fill=False )
        pdf.cell(w=70,h=5,txt='No. de Dui '+ str(cdg.ids.perfil.dui) if hasattr(cdg, 'nombrecc') else '', border='B', align='C', fill=False )  
        pdf.cell(w=37,h=5,txt=' ', border='B', align='L', fill=False )     
        pdf.cell(w=20,h=5,txt=' ', border='B', align='L', fill=False )
        pdf.cell(w=60,h=5,txt=' ', border='B', align='L', fill=False )
        pdf.cell(w=5,h=5,txt=' ', border='RB', align='L', fill=False, ln=1 )
        pdf.set_text_color(255,255,255)
        pdf.cell(w=196,h=6,txt='PARA USO EXCLUSIVO DE ASOCIACION HPH EL SALVADOR', border=1,  align='C', fill=True, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=106,h=5,txt='CONFIRMACIÓN DE DATOS ', border='LRT', align='C', fill=False)
        pdf.cell(w=20,h=5,txt='Verificado por: ', border='L', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=70,h=5,txt=' '+ cpus.verificadopor if hasattr(cpus, 'verificadopor') else '', border='R', align='L', fill=False , ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=106,h=5,txt='¿Validé finmas, nombres y fotografía según documentos legales ? ', border='LR', align='C', fill=False)
        pdf.cell(w=30,h=5,txt='Código de empleado/a: ', border='L', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=60,h=5,txt=' '+ cpus.codigoe if hasattr(cpus, 'codigoe') else '' , border='R', align='L', fill=False , ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=106,h=5,txt='' , border='LRB', align='C', fill=False)
        pdf.set_xy(40, 174)
        if  cpus!="" and cpus.valedefnf =='Si':
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(45, 175)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(55, 174)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(62, 175)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            #pdf.set_xy(148, 77)
            #pdf.multi_cell(w=0,h=5, txt='', border=0)
        else:
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(45, 175)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(55, 174)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(62, 175)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(148, 77)
            #pdf.multi_cell(w=0,h=5, txt='', border=0)
        

        pdf.set_xy(116, 174)
        pdf.cell(w=90,h=5,txt='' , border='LRB', align='L', fill=False, ln=1)
        pdf.set_xy(10,178)
        pdf.multi_cell(w=106,h=6,txt='¿Verifiqué la dirección presentada con el documento de identidad personal,  coincide con la señalada por el cliente  ? ', border='LR', align='C', fill=False)
        pdf.set_xy(116,179)        
        pdf.multi_cell(w=0,h=5,txt='', border='LRT', align='C', fill=False)
        pdf.cell(w=106,h=5,txt='' , border='LR', align='L', fill=False)
        pdf.cell(w=5,h=5,txt='F. ' , border='L', align='L', fill=False )
        pdf.cell(w=80,h=5,txt='' , border='B', align='L', fill=False )
        pdf.multi_cell(w=0,h=5,txt='' , border='R', align='L', fill=False)
        pdf.cell(w=106,h=5,txt='', border='LR', align='C', fill=False)
        pdf.cell(w=90,h=5,txt='Firma del Ejecutivo' , border='LR', align='C', fill=False, ln=1)
        pdf.cell(w=106,h=5,txt='', border='LRB', align='C', fill=False)
        pdf.set_xy(40, 191)
        if  cpus!="" and cpus.valedefnf =='Si':
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(45, 192)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(55, 191)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(62, 192)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            #pdf.set_xy(148, 77)
            #pdf.multi_cell(w=0,h=5, txt='', border=0)
        else:
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(45, 192)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(55, 191)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(62, 192)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            #pdf.set_xy(148, 77)
            #pdf.multi_cell(w=0,h=5, txt='', border=0)
        

        pdf.set_xy(116, 194)
        pdf.cell(w=90,h=5,txt='' , border='LRB', align='L', fill=False)
       
     
        pdf.output('ConozcaC.pdf', 'F')
        return FileResponse(open('ConozcaC.pdf', 'rb'), as_attachment=True, content_type='application/pdf')
