# Generated by Django 3.2.5 on 2023-07-20 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClienteApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangoHis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minimo', models.FloatField(max_length=10)),
                ('maximo', models.FloatField(max_length=10)),
                ('tipo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'RangoHis',
                'verbose_name_plural': 'RangoHis',
                'db_table': 'rangohis',
            },
        ),
        migrations.CreateModel(
            name='RegHis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje', models.FloatField(max_length=5)),
                ('fecha', models.DateField()),
                ('idRango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HistorialApp.rangohis')),
                ('idperfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClienteApp.perfil')),
            ],
            options={
                'verbose_name': 'RegHis',
                'verbose_name_plural': 'RegHis',
                'db_table': 'reghis',
            },
        ),
    ]
