# Generated by Django 3.2.5 on 2023-03-08 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('dui', models.CharField(max_length=12)),
                ('telefono', models.CharField(max_length=10)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('fechan', models.DateField()),
                ('edad', models.IntegerField()),
                ('salario', models.FloatField(max_length=8)),
                ('direccion', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=40)),
                ('contrasena', models.CharField(max_length=500)),
                ('rcontrasena', models.CharField(max_length=500)),
                ('estado', models.CharField(max_length=10)),
                ('fechaR', models.DateField(auto_now_add=True)),
                ('estadosv', models.CharField(max_length=10)),
                ('estadosm', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfils',
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Perfilna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('dui', models.CharField(max_length=12)),
                ('telefono', models.CharField(max_length=10)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('edad', models.IntegerField()),
                ('salario', models.FloatField(max_length=7)),
                ('fechaR', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'perfilna',
                'verbose_name_plural': 'perfilnas',
                'db_table': 'Perfilna',
            },
        ),
        migrations.CreateModel(
            name='perfildetalle',
            fields=[
                ('iddetalle', models.AutoField(primary_key=True, serialize=False)),
                ('fecharegistro', models.DateTimeField(auto_now_add=True)),
                ('comunidad', models.CharField(max_length=60)),
                ('area', models.CharField(max_length=10)),
                ('tipo', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClienteApp.perfil')),
            ],
            options={
                'verbose_name': 'perfildetalle',
                'verbose_name_plural': 'perfildetalles',
                'db_table': 'perfildetalle',
            },
        ),
    ]
